config/routes.rb
Rails.application.routes.draw do
  resources :roles
  resources :users, path: '/customers', controller: 'customers', only: [:index, :show, :edit, :update]
  get '/account', to: 'accounts#show'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users

  validates :name, :code, presence: true, uniqueness: true

  def customer?
    code == 'C'
  end

  def manager?
    code == 'M'
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  load_and_authorize_resource
  before_action :set_role, only: %i[ show edit update destroy ]

  # GET /roles or /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1 or /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles or /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: "Role was successfully created." }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1 or /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: "Role was successfully updated." }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1 or /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: "Role was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def role_params
      params.require(:role).permit(:name, :code)
    end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.haml
= form_for @role do |f|
  - if @role.errors.any?
    = errors_for @role

  .form-group.mt-4
    = f.label 'Name of the Role', class: 'required'
    = f.text_field :name, class: 'form-control', required: true

  .form-group.mt-4
    = f.label 'Role Code', class: 'required'
    = f.text_field :code, class: 'form-control', required: true

  = f.submit 'Save', class: 'btn btn-primary'

app/views/roles/edit.html.haml
.card
  .card-header 
    .flex.flex-wrap.justify-between 
      Editing role
      = link_to 'Back', :back, class: 'btn btn-sm btn-red'
  .card-body
    = render 'form'

app/views/roles/index.html.haml
.card
  .card-header 
    .flex.flex-wrap.justify-between
      Roles
      = link_to 'New Role', new_role_path, class: 'btn btn-sm btn-primary'
  %table.min-w-full.border-r.border-l.rounded-b.border-gray-200
    %thead
      %tr
        %th.t-head Name
        %th.t-head Code
        %th.t-head

    %tbody
      - @roles.each do |role|
        %tr
          %td.t-row= role.name
          %td.t-row= role.code
          %td.t-row
            = link_to 'Show', role, class: 'btn btn-light btn-sm'
            - if can? :edit, role
              = link_to 'Edit', edit_role_path(role), class: 'btn btn-light btn-sm'
              
            - if can? :destroy, role
              = link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-light btn-sm'

%br

app/views/roles/new.html.haml
.card
  .card-header 
    .flex.flex-wrap.justify-between 
      New role
      = link_to 'Back', :back, class: 'btn btn-sm btn-red'
  .card-body
    = render 'form'

app/views/roles/show.html.haml
.card
  .card-header
    .flex.justify-between
      = "Role ##{@role.id}"
      #actions
        = link_to 'Edit', edit_role_path(@role), class: 'btn btn-sm btn-light'
        = link_to 'Back', :back, class: 'btn btn-sm btn-red'
  .card-body
    %p Name: #{@role.name}
    %p Code: #{@role.code}